/**:
  ros__parameters:
    filter_target_label:
      UNKNOWN : true
      CAR : true
      TRUCK : true
      BUS : true
      TRAILER : true
      MOTORCYCLE : true
      BICYCLE : true
      PEDESTRIAN : true

    filter_settings:
      # polygon overlap based filter
      polygon_overlap_filter:
        enabled: true
      # velocity direction based filter
      lanelet_direction_filter:
        enabled: false
        velocity_yaw_threshold: 0.785398 # [rad] (45 deg)
        object_speed_threshold: 3.0 # [m/s]
